#!/usr/bin/env bash

# Documentation can be found here: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html
# Exit immediately if any command returns a non-zero status.
set -e 

BUCKET_NAME=$1

# A quick description of what is going to happen.
echo "Create S3 Bucket named: $BUCKET_NAME."

## Checking to see if at least one argument is provided
if [ -z "$1" ]; then
   echo "The needs to be a bucket name eg. ./create-bucket my-bucket-name."
   exit 1
fi

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ca-central-1" \
--query "Location" \
--output "text"

echo "S3 Bucket named: $BUCKET_NAME created."